// GENERATED by scripts/generate-compat-probes.py -- do not edit.
//
// One `using ::Name;` per public engine name, taken from the engine
// headers rather than from the bridge. Including this after
// <stormengine2/compat/global.h> fails to compile if the bridge does
// not re-export a name, which is the property the compat spec claims
// and could not previously deliver: the hand-written list named a
// third of the exports, so a name missing from the bridge was missing
// from the spec too.
//
// 133 names.
#pragma once

namespace storm_compat_probe {
using ::ActionBinding;
using ::ActionMap;
using ::ActionSources;
using ::AnimationComponent;
using ::AnimationSystem;
using ::AssetStore;
using ::AssetStore_Ptr;
using ::BoxColliderComponent;
using ::Component;
using ::ComponentMiss;
using ::ComponentMissDescription;
using ::Contact;
using ::ContactAABB;
using ::ContactSystem;
using ::DpadFromPoint;
using ::ECS_MAX_DIAGNOSTIC_REPORTS;
using ::EcsComponentIdIsValid;
using ::EcsFallbackComponent;
using ::EcsReportErr;
using ::EcsShouldReport;
using ::EcsSuppressionNote;
using ::Entity;
using ::EntityOrder;
using ::EvalTouches;
using ::EvalVPad;
using ::FPS;
using ::GameState;
using ::GameStateMachine;
using ::Gamepad;
using ::GamepadButton;
using ::GamepadDown;
using ::GamepadNormaliseStick;
using ::GamepadPressed;
using ::GamepadReleased;
using ::GamepadState;
using ::IComponent;
using ::IPool;
using ::Keyboard;
using ::LOG_ERROR;
using ::LOG_INFO;
using ::LOG_WARNING;
using ::LoadTexturesFromXml;
using ::LogEntry;
using ::LogType;
using ::Logger;
using ::Logger_Ptr;
using ::MAX_COMPONENTS;
using ::MILLISECS_PER_FRAME;
using ::MakeDefaultZones;
using ::MakeVPadLayout;
using ::Map;
using ::MovementSystem;
using ::NetAddress;
using ::NetAddressFromParts;
using ::NetAddressToString;
using ::NetChunk;
using ::NetChunkFlag;
using ::NetChunkHeader;
using ::NetClient;
using ::NetConnection;
using ::NetControlMessage;
using ::NetControlPacket;
using ::NetIpToHost;
using ::NetMessageReader;
using ::NetMessageWriter;
using ::NetNonce32;
using ::NetNowMs;
using ::NetPacketFlag;
using ::NetPacketHeaderPack;
using ::NetPacketHeaderUnpack;
using ::NetPortToHost;
using ::NetRandom32;
using ::NetResolveAddress;
using ::NetSendControl;
using ::NetServer;
using ::NetSnapshot;
using ::NetSnapshotCache;
using ::NetSnapshotDelta;
using ::NetSocket;
using ::NetVarIntPack;
using ::NetVarIntUnpack;
using ::NonceToToken;
using ::Pool;
using ::Registry;
using ::RenderColliderSystem;
using ::RenderSystem;
using ::RigidBodyComponent;
using ::Signature;
using ::SpriteComponent;
using ::System;
using ::Text;
using ::Tile;
using ::TileMapLoader;
using ::TokenToNonce;
using ::TouchControl;
using ::TouchInput;
using ::TouchPoint;
using ::TouchZone;
using ::TouchZones;
using ::TransformComponent;
using ::VPadControl;
using ::VPadLayout;
using ::VPadState;
using ::VPadStyle;
using ::XmlLoader;
using ::XmlObjectDef;
using ::XmlTextureDef;
using ::kNetChunkResend;
using ::kNetChunkVital;
using ::kNetControlAccept;
using ::kNetControlClose;
using ::kNetControlConnect;
using ::kNetControlConnectAccept;
using ::kNetControlConnectReady;
using ::kNetControlMagic;
using ::kNetFlushMs;
using ::kNetHandshakeRetryMs;
using ::kNetHardResendMs;
using ::kNetKeepaliveMs;
using ::kNetMaxChunkSize;
using ::kNetMaxChunksPerPacket;
using ::kNetMaxClients;
using ::kNetMaxClientsPerIp;
using ::kNetMaxPacketSize;
using ::kNetMaxPayload;
using ::kNetMaxSequence;
using ::kNetPacketResend;
using ::kNetResendBufferSize;
using ::kNetResendMaxEntries;
using ::kNetResendMs;
using ::kNetSequenceBits;
using ::kNetTimeoutMs;
using ::kNetVarIntMaxBytes;
} // namespace storm_compat_probe
