FROM storminator16/igloo-testing-devkitpro:latest

ENV DEVKITPRO=/opt/devkitpro
ENV DEVKITARM=${DEVKITPRO}/devkitARM
ENV DEVKITPPC=${DEVKITPRO}/devkitPPC
ENV DEVKITA64=${DEVKITPRO}/devkitA64
ENV PATH=${DEVKITPRO}/devkitA64/bin:${DEVKITPRO}/tools/bin:$PATH
ENV PKG_CONFIG_PATH=${DEVKITPRO}/portlibs/switch/lib/pkgconfig:${DEVKITPRO}/libnx/lib/pkgconfig

# # Copy the source code into the container
RUN mkdir -p /opt/library
COPY ./common /opt/library/common
COPY ./vendor /opt/library/vendor
COPY ./specs /opt/library/specs
COPY ./Makefile.nx /opt/library/Makefile
COPY ./base.mk /opt/library/base.mk
COPY ./examples/nx-platformer /opt/library/examples/nx-platformer

# Build the project
WORKDIR /opt/library
CMD ["make", "test"]