#include "game.h"

#include <SDL2/SDL_image.h>

#include <sys/stat.h>

#include "states/battleState.h"
#include "states/gameOverState.h"
#include "states/menuState.h"
#include "states/overworldState.h"

namespace {

// One file that only exists if the artwork has been downloaded. See
// assets/README.md -- this example ships code only, because Tiny Swords may not
// be redistributed.
const char *const kSentinelAsset = "./assets/gfx/units/blue/Warrior_Run.png";

bool FileExists(const char *path) {
  struct stat st;
  return ::stat(path, &st) == 0;
}

} // namespace

Game::Game() {
  assetStore_ = std::make_unique<AssetStore>();
  logger_ = std::make_unique<Logger>();
}

Game::~Game() {}

bool Game::LoadAssets() {
  // Checked before anything is loaded, and fatal rather than logged. Both of
  // the engine's misses here are quiet: AssetStore::AddTexture logs and
  // carries on, and GetTexture hands back nullptr at the point of use. Without
  // this guard a missing download is a black window with no explanation.
  if (!FileExists(kSentinelAsset)) {
    logger_->Err("Artwork not found.");
    logger_->Err(std::string("Expected: ") + kSentinelAsset);
    logger_->Err("This example ships code only -- Tiny Swords may not be");
    logger_->Err("redistributed. Download the free pack from");
    logger_->Err("  https://pixelfrog-assets.itch.io/tiny-swords");
    logger_->Err("and follow examples/strategy/assets/README.md.");
    return false;
  }

  struct Asset {
    const char *id;
    const char *path;
  };
  static const Asset kAssets[] = {
      // Units, one texture per animation. Tiny Swords ships each animation as
      // its own horizontal strip, which is exactly what AnimationComponent
      // walks with vertical = false -- no sheet repacking, no cell table.
      // Only what is actually drawn. A missing texture is fatal below, so
      // every entry here is a file the download instructions must ask for --
      // loading the idle strips, the towers and the dust effect "just in case"
      // would have made the game refuse to start over art it never draws.
      {"blue_warrior_run", "./assets/gfx/units/blue/Warrior_Run.png"},
      {"blue_warrior_attack", "./assets/gfx/units/blue/Warrior_Attack1.png"},
      {"blue_archer_run", "./assets/gfx/units/blue/Archer_Run.png"},
      {"blue_archer_attack", "./assets/gfx/units/blue/Archer_Shoot.png"},
      {"red_warrior_run", "./assets/gfx/units/red/Warrior_Run.png"},
      {"red_warrior_attack", "./assets/gfx/units/red/Warrior_Attack1.png"},
      {"red_archer_run", "./assets/gfx/units/red/Archer_Run.png"},
      {"red_archer_attack", "./assets/gfx/units/red/Archer_Shoot.png"},

      // Buildings. Ownership is a swap of assetId on one SpriteComponent.
      {"castle_blue", "./assets/gfx/buildings/blue/Castle.png"},
      {"castle_red", "./assets/gfx/buildings/red/Castle.png"},
      {"castle_neutral", "./assets/gfx/buildings/neutral/Castle.png"},

      {"tilemap", "./assets/gfx/terrain/tilemap.png"},
      {"water", "./assets/gfx/terrain/water.png"},

      // Scenery. Tree and bush are animated strips; rock is a single tile.
      {"tree", "./assets/gfx/deco/tree.png"},
      {"bush", "./assets/gfx/deco/bush.png"},
      {"rock", "./assets/gfx/deco/rock.png"},

      {"explosion", "./assets/gfx/fx/explosion.png"},

      // Generated by assets/gen-ui.sh, and the only images this example owns.
      {"digits", "./assets/ui/digits.png"},
      {"title", "./assets/ui/title.png"},
      {"menu_start", "./assets/ui/menu_start.png"},
      {"menu_quit", "./assets/ui/menu_quit.png"},
      {"day", "./assets/ui/day.png"},
      {"cmd_charge", "./assets/ui/cmd_charge.png"},
      {"cmd_hold", "./assets/ui/cmd_hold.png"},
      {"cmd_volley", "./assets/ui/cmd_volley.png"},
      {"cmd_retreat", "./assets/ui/cmd_retreat.png"},
      {"victory", "./assets/ui/victory.png"},
      {"defeat", "./assets/ui/defeat.png"},
      {"win", "./assets/ui/win.png"},
      {"lose", "./assets/ui/lose.png"},
      {"hint_map", "./assets/ui/hint_map.png"},
      {"hint_battle", "./assets/ui/hint_battle.png"},
      {"confirm_retreat", "./assets/ui/confirm_retreat.png"},
      {"confirm_body", "./assets/ui/confirm_body.png"},
      {"confirm_hint", "./assets/ui/confirm_hint.png"},
  };

  // A missing texture is fatal, not a warning. The sentinel above only proves
  // one file arrived; a partial copy would otherwise reach the game as a
  // silent black window, because AddTexture logs and continues and GetTexture
  // hands back nullptr at the point of use.
  int missing = 0;
  for (const auto &a : kAssets) {
    assetStore_->AddTexture(renderer_, a.id, a.path);
    if (!assetStore_->GetTexture(a.id)) {
      logger_->Err(std::string("Missing ") + a.path +
                   " -- run from the game root.");
      ++missing;
    }
  }
  if (missing > 0) {
    logger_->Err(std::to_string(missing) +
                 " texture(s) failed to load; see "
                 "examples/strategy/assets/README.md.");
    return false;
  }
  return true;
}

void Game::Initialize(StartState start) {
  if (SDL_Init(SDL_INIT_EVERYTHING) != 0) {
    logger_->Err("Error initializing SDL.");
    return;
  }

  window_ =
      SDL_CreateWindow("Realms", SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                       windowWidth_, windowHeight_, 0);
  if (!window_) {
    logger_->Err("Error creating SDL window.");
    return;
  }

  // Window icon, set before the artwork check on purpose: it is one of the
  // images this example owns (assets/gen-ui.sh draws it), so it is present
  // even on the run where the player has not downloaded Tiny Swords yet and
  // LoadAssets is about to refuse to start.
  //
  // SDL_SetWindowIcon copies the surface, so it is freed immediately --
  // holding it would leak. Loaded through SDL_image rather than the
  // AssetStore, which deals in textures and cannot hand back a surface.
  if (SDL_Surface *icon = IMG_Load("./assets/ui/icon.png")) {
    SDL_SetWindowIcon(window_, icon);
    SDL_FreeSurface(icon);
  } else {
    // Not fatal: the game runs fine with the window manager's default.
    logger_->Err("Missing ./assets/ui/icon.png -- run from the game root.");
  }

  renderer_ = SDL_CreateRenderer(
      window_, -1, SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC);
  if (!renderer_) {
    logger_->Err("Error creating SDL renderer.");
    return;
  }

  if (!LoadAssets()) {
    // isRunning_ stays false, so Run() returns without entering the loop
    // and main() reports a non-zero exit.
    return;
  }

  gamepad_.OpenFirstAttached();
  if (gamepad_.Connected()) {
    logger_->Log("Controller: " + gamepad_.Name());
  }

  campaign_.Reset();

  // The state machine owns every state pointer -- pass `new`-allocated states
  // and never delete them yourself.
  GameState *first = nullptr;
  switch (start) {
  case StartState::Overworld:
    first = new OverworldState(
        renderer_, windowWidth_, windowHeight_, isDebugging_, assetStore_.get(),
        &gameStateMachine_, &gamepad_, &campaign_, isRunning_);
    break;
  case StartState::Battle:
    // Straight into a fight between the two opening Warrior generals, so
    // the battle screen can be worked on without driving the map first.
    campaign_.result = world::BattleResult{};
    first = new BattleState(
        renderer_, windowWidth_, windowHeight_, isDebugging_, assetStore_.get(),
        &gameStateMachine_, &gamepad_, &campaign_,
        /*attacker=*/0, /*defender=*/3, /*castle=*/1, isRunning_);
    break;
  case StartState::GameOver:
    first =
        new GameOverState(renderer_, windowWidth_, windowHeight_, isDebugging_,
                          assetStore_.get(), &gameStateMachine_, &gamepad_,
                          &campaign_, world::Owner::Blue, isRunning_);
    break;
  case StartState::Menu:
  default:
    first = new MenuState(renderer_, windowWidth_, windowHeight_, isDebugging_,
                          assetStore_.get(), &gameStateMachine_, &gamepad_,
                          &campaign_, isRunning_);
    break;
  }
  gameStateMachine_.changeState(first);

  isRunning_ = true;
}

bool Game::Run(StartState start) {
  Initialize(start);
  if (!isRunning_) {
    return false; // Initialize failed and already said why.
  }
  while (isRunning_) {
    ProcessInput();
    Update();
    Render();
  }
  return true;
}

void Game::ProcessInput() { gameStateMachine_.processInput(); }
void Game::Update() { gameStateMachine_.update(); }
void Game::Render() { gameStateMachine_.render(); }

void Game::Destroy() {
  gameStateMachine_.clean();
  // Before SDL_QuitSubSystem: SDL_GameControllerQuit frees every open
  // controller, so releasing the pad afterwards is a use-after-free.
  gamepad_.Shutdown();
  if (assetStore_) {
    assetStore_->ClearAssets();
  }
  SDL_DestroyRenderer(renderer_);
  SDL_DestroyWindow(window_);
  SDL_QuitSubSystem(SDL_INIT_EVERYTHING);
  SDL_Quit();
}
